Repository PrisKompis/PrisKompis, pull requests merged in 2019-05, with the labels that each got.

#15 Convert constraint to linearlayout inshop activity. Removed Autofocus…
  app/src/main/java/com/example/priskompis/InShop.java
  app/src/main/res/layout/activity_in_shop.xml
Labels: enhancement

#35 Fixed issue #34 Implemented null check for card input
  app/src/main/java/com/example/priskompis/Payment.java
Labels: bug

#37 layout designs for the rest of the activities
  app/src/main/res/drawable/edittext_bgalt.xml
  app/src/main/res/layout/activity_budget_set.xml
  app/src/main/res/layout/activity_checkout.xml
  app/src/main/res/layout/activity_in_shop.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_payment.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/layout_products.xml
Labels: enhancement

#38 Added Toast message saying payment is successful
  app/src/main/java/com/example/priskompis/Payment.java
Labels: enhancement

#39 fixed minor layout issue
  app/src/main/java/com/example/priskompis/InShop.java
  app/src/main/res/layout/activity_in_shop.xml
Labels: enhancement

#42 added functionality to alert when budget exceeded shopping
  app/src/main/java/com/example/priskompis/InShop.java
  app/src/main/java/com/example/priskompis/Popup.java
  app/src/main/res/layout/alert_dialog.xml
Labels: enhancement

#45 Dtsamis
  app/src/main/java/com/example/priskompis/Adapter/ProductAdapter.java
  app/src/main/res/layout/layout_products.xml
Labels: enhancement

#46 fixed bug from popup
  app/src/main/java/com/example/priskompis/InShop.java
  app/src/main/res/layout/alert_dialog.xml
Labels: enhancement

#47 minor changes in styles
  app/src/main/res/drawable/button_background.xml
  app/src/main/res/layout/activity_budget_set.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_payment.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/alert_dialog.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#48 Renamed label in Inshop and removed unused layouts and java files
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/priskompis/AppCompatPreferenceActivity.java
  app/src/main/java/com/example/priskompis/InShop.java
  app/src/main/java/com/example/priskompis/ProductSelection.java
  app/src/main/java/com/example/priskompis/ShoppingCart.java
  app/src/main/java/com/example/priskompis/ShoppingList.java
  app/src/main/res/layout/activity_checkout.xml
  app/src/main/res/layout/activity_in_shop.xml
  app/src/main/res/layout/activity_product_selection.xml
  app/src/main/res/layout/activity_shopping_cart.xml
  app/src/main/res/layout/activity_shopping_list.xml
Labels: enhancement

#52 changed app icon, adjusted logo in actionbar
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-web.png
  app/src/main/java/com/example/priskompis/BarcodeCaptureActivity.java
  app/src/main/java/com/example/priskompis/BudgetSet.java
  app/src/main/java/com/example/priskompis/InShop.java
  app/src/main/java/com/example/priskompis/Payment.java
  app/src/main/java/com/example/priskompis/ShoppingCart.java
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/icon36.png
  app/src/main/res/drawable/icon72.png
  app/src/main/res/layout/activity_shopping_cart.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_launcher_background.xml
Labels: enhancement

#53 fixed barcode scanning layout
  app/src/main/java/com/example/priskompis/BarcodeCaptureActivity.java
  app/src/main/java/com/example/priskompis/ui/camera/CameraSourcePreview.java
  app/src/main/res/layout/barcode_capture.xml
Labels: enhancement

#54 Update README.md
  README.md
Labels: good first issue

#55 Edit Alignments in Readme
  README.md
Labels: Documentation

#57 Feature/delete cart item
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/priskompis/Adapter/ProductAdapter.java
  app/src/main/java/com/example/priskompis/InShop.java
  app/src/main/java/com/example/priskompis/LoginActivity.java
  app/src/main/java/com/example/priskompis/Model/Order.java
  app/src/main/java/com/example/priskompis/Operations/Database.java
  app/src/main/java/com/example/priskompis/Operations/ShoppingCart.java
  app/src/main/java/com/example/priskompis/ShoppingCart.java
Labels: enhancement

#60 fixing bug #59 price display
  app/src/main/java/com/example/priskompis/InShop.java
  app/src/main/java/com/example/priskompis/ShoppingCart.java
Labels: bug

#62 fixed the message display in scan next item page
  app/src/main/java/com/example/priskompis/InShop.java
Labels: bug

#66 Fixed payment failure validation
  app/src/main/java/com/example/priskompis/Payment.java
Labels: bug

#68 fixed sending receipt to new user registered
  app/src/main/java/com/example/priskompis/LoginActivity.java
  app/src/main/java/com/example/priskompis/SignUp.java
  build.gradle
Labels: bug
